siteMetadata:
  title    : 'RethinkDB'
  fullTitle: 'Rebirth DB: the open-source database for the realtime web'
  keywords : 'RethinkDB, Rebirth, Rethink, RethinkDB, database, real-time, scalable, open-source'

index:
  twitterAccount: '@rethinkdb'
  githubLink: 'https://github.com/RethinkDB/rethinkdb'
  releaseLink: 'https://github.com/RethinkDB/rethinkdb/releases'
  sponsorsLinks:
    - image: 'aidax.png'
      link: 'http://www.aidaxbi.com'
    - image: 'zerotier.png'
      link: 'https://www.zerotier.com'

docsCategoriesOrder:
  - Getting started
  - The ReQL query language
  - The RethinkDB data model
  - ReQL in practice
  - Administration
  - Deployment
  - Troubleshooting
  - Integration
  - RethinkDB architecture
