siteMetadata:
  title    : 'RebirthDB'
  fullTitle: 'Rebirth DB: the open-source database for the realtime web'
  keywords : 'RebirthDB, Rebirth, Rethink, RethinkDB, database, real-time, scalable, open-source'

index:
  twitterAccount: '@rebirthdb'
  githubLink: 'https://github.com/RebirthDB/rebirthdb'
  releaseLink: 'https://github.com/RebirthDB/rebirthdb/releases'
